package com.ecokeen.backend.api;

import com.ecokeen.backend.crudRepositories.GroceryRepository;
import com.ecokeen.backend.crudRepositories.TravelRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RequestMapping("api/v1/groceries")
@RestController
public class GroceryController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GroceryRepository groceryRepository;

    @PostMapping(path="add/{id}") // Map ONLY POST Requests
    public @ResponseBody
    Boolean addGroceryHistory (@RequestParam String name,
                              @RequestParam Integer quantity,
                              @RequestParam String product) {

        return true;
    }

    @GetMapping(path="/history/{id}")
    public @ResponseBody String getGroceryHistory(
            @PathVariable("id") Integer id) {
        // SELECT * FROM Travel WHERE User.id = id
        return "/all/id";
    }

    @GetMapping(path="/footprint/{id}")
    public @ResponseBody Integer getGroceryFootprint(
            @PathVariable("id") Integer id) {
        // SELECT footprint FROM grocery WHERE user.id = id
        return -1;
    }

}