package com.ecokeen.backend.api;

import com.ecokeen.backend.crudRepositories.TravelRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RequestMapping("api/v1/travels")
@RestController
public class TravelController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TravelRepository travelRepository;

    @PostMapping(path="add/{id}") // Map ONLY POST Requests
    public @ResponseBody Boolean addTravelHistory (@RequestParam String name,
                                        @RequestParam String carBrand,
                                        @PathVariable("id") Integer id,
                                        @RequestParam String email,
                                        @RequestParam String carType,
                                        @RequestParam String petrolType) {

        return true;
    }

    @GetMapping(path="/history/{id}")
    public @ResponseBody String getTravelHistory(
            @PathVariable("id") Integer id) {
        // SELECT * FROM Travel WHERE User.id = id
        return "/all/id";
    }

    @GetMapping(path="/footprint/{id}")
    public @ResponseBody Integer getTravelFootprint(
            @PathVariable("id") Integer id) {
        // SELECT footprint FROM travel WHERE user.id = id
        return -1;
    }

}